### ISSUE TITLE
[FEEDBACK] Tutorial 11 Window Resizing : Brendan Galea

### ISSUE THREAD

**Issue by yeokaiwei** [blurrypiano/littleVulkanEngine#22]
Hi Brenda,
I can't get the same results with windows resizing as Tutorial 11 in Visual Studio 2019.

What happens is that when you try to resize, the app stops running and the triangle stops rotating.

If you contract and expand the window, "artifacts" will remain and black zones with appear.

Once you release the mouse click, the window will resize and the app resets correctly.

I've attached a video to let you see what it is. 

Is this Windows specific? 

https://user-images.githubusercontent.com/36597018/147419579-56351206-e7cc-4038-ac2f-34ee3c987e4a.mp4

**Comment by blurrypiano** [comment]
Yup this is due to windows and how resizing is handled by glfw (the thread blocks). For smooth resizing we would require a more complicated implementation that makes use of multiple threads.

Also this isn't the place to be asking questions such as this. Please either comment on the youtube videos or ask on our discord: https://discord.gg/CUQkuKsszr

Sorry but for future issues reported here such as this I'll be closing without comment.

**Comment by yeokaiwei** [comment]
Thanks for the reply.

Apologies for posting it here but there's a reason for it.

I can't post a video into the Youtube comments.

I would have to create a link and post separately.

**Comment by blurrypiano** [comment]
ok no worries! I recommend joining the discord then, videos can be shared there!
